apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
spec:
  template:
    spec:
      containers:
      - name: test-job 
        image: wurssb/unlock_fastp
        args:
        - -c
        - {{ path }}
        resources:
          requests:
            memory: "4Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "1"
      restartPolicy: OnFailure
