apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-job-spawner
imagePullSecrets:
- name: regcred
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-job-spawner
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["update", "get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-binding-job-spawner
subjects:
- kind: ServiceAccount
  name: sa-job-spawner
roleRef:
  kind: Role
  name: role-job-spawner
  apiGroup: rbac.authorization.k8s.io
